#pragma once

#include <QWidget>
#include <QVBoxLayout>
#include <QImage>
#include <QLabel>
#include <QMimeDatabase>
#include <QFile>
#include <QTextEdit>
#include <QtConcurrent/QtConcurrent>
#include <QPromise>
#include <QFutureWatcher>
#include <QStackedWidget>
#include <QTimer>
#include <QHash>
#include <archive.h>
#include <archive_entry.h>
#include <qtypes.h>
#include <QDockWidget>
#include "../sol/sol.hpp"
