#pragma once

#include <unistd.h>
#include <QIcon>
#include <QFuture>
#include <QFutureWatcher>
#include <QApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHBoxLayout>
#include <QHash>
#include <QInputDialog>
#include <QKeySequence>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QShortcut>
#include <QSplitter>
#include <QStringListModel>
#include <QTextEdit>
#include <QVBoxLayout>
#include <QWidget>
#include <QRegularExpression>
#include <QStandardPaths>
#include <QDebug>
#include <QStringView>
#include <QActionGroup>
#include <QEvent>
#include <QMessageBox>
#include <QInputDialog>
#include "InputDialog.hpp"
#include <QKeyEvent>
#include <QtConcurrent/QtConcurrent>
#include <QPromise>
#include <QFuture>
#include <QThread>
#include <QClipboard>
#include <QToolBar>
#include <QSet>
#include <QHash>
#include <unordered_map>
