#pragma once

#include <QContextMenuEvent>
#include <QDesktopServices>
#include <QHash>
#include <QInputDialog>
#include <QKeyEvent>
#include <QKeySequence>
#include <QMenu>
#include <QMimeType>
#include <QMimeData>
#include <QMimeDatabase>
#include <QMessageBox>
#include <QModelIndexList>
#include <QObject>
#include <QRegularExpression>
#include <QSet>
#include <QShortcut>
#include <QThread>
#include <QTimer>
#include <QVBoxLayout>
#include <QWidget>
#include <QProcess>
#include <QTemporaryFile>
#include <QWheelEvent>
#include <QMouseEvent>
#include <QApplication>
#include <QUrl>
#include <QCryptographicHash>
